apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-catalogue-pod
  template:
    metadata:
      labels:
        app: mongo-catalogue-pod
    spec:
      containers:
        - name: container-catalogue-mongodb
          image: yassinehriz/microservice-catalogue-database:v1
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: pass

